Gaudi OpenShift notebook container
intel/ai-containers pull request #365
Opened 2024-09-06 21:14 UTC by sharvil10

This PR adds the Dockerfiles for notebook container for OpenShift AI.

2024-09-06 22:03 UTC, tylertitsworth requested changes
Do we need a plan for OpenShift manifest validation?

2024-09-06 22:03 UTC, tylertitsworth commented on enterprise/redhat/openshift-ai/gaudi/docker/docker-compose.yaml
Few things need to be address in future PRs:
1. build-container compatibility
2. test-containers compatibility (tests.yaml)
3. Integration with mkdocs (labels)

2024-09-06 22:03 UTC, tylertitsworth commented on enterprise/redhat/openshift-ai/gaudi/docker/requirements.txt
can you add to dependabot.yml?

2024-09-10 16:53 UTC, sharvil10 commented on enterprise/redhat/openshift-ai/gaudi/docker/requirements.txt
Added

2024-09-10 16:54 UTC, sharvil10 commented on enterprise/redhat/openshift-ai/gaudi/docker/docker-compose.yaml
Will do in a future PR.

2024-09-10 16:56 UTC, tylertitsworth requested changes
small nit

2024-09-10 16:56 UTC, tylertitsworth commented on .github/dependabot.yml
> +      preset:
Choose a group name that is relevant.

2024-09-10 17:03 UTC, tylertitsworth approved these changes

2024-09-10 17:03 UTC, merged